Unit testing and refactoring of object pool loading
Open-Agriculture/AgIsoStack-rs pull request #27
Opened 2023-11-03 18:08 UTC by JannesBrands

Started to create some unit testing for loading iop. I am starting to refactor the Object Pool Reader implementation to assign the unit tests more direct to the different object types. More results will follow soon as I am in vacation.

2023-11-05 09:34 UTC, GwnDaan requested changes

2023-11-05 09:34 UTC, GwnDaan commented on src/object_pool/reader.rs
> +
todo: remove debug

2023-11-05 09:34 UTC, GwnDaan commented on src/object_pool/mod.rs
> +    ScaledGraphic(ScalesGraphic),
todo: remove this change, I think you meant to put here `ScaledGraphic` as well, like your other corrections

2023-11-05 09:34 UTC, GwnDaan commented on src/object_pool/mod.rs
> +}
praise: I like the use of the BitVec library here, looks really neat!

2023-11-05 09:34 UTC, GwnDaan commented on src/object_pool/object_pool.rs
> +    fn test_from_iop() {
suggestion: https://github.com/Open-Agriculture/AgIsoStack-rs/pull/23#issuecomment-1783763094

> My suggestion: unit test the objects directly from a hex string/array. E.g. pass the hex array directly to the de-serialization method for each object individually, and then test it's contents. Then the other way around can be unit tested easily and maintainable as well, by simply serializing the same 'de-serialized' object again and checking if it equals the defined hex array used at the start.
I'm sure we can do a small unit test for the from_iop() that maybe checks the number of objects present in the parsed pool, but doesn't have to check the contents of it. As that should really be done somewhere else in smaller parts IMO.

2023-11-05 09:36 UTC, GwnDaan commented
Also I suggest having a look at the failed pipelines, they seems to have some suggestions as well

2023-11-05 09:41 UTC, JannesBrands commented
Yep, completely agree. Keep in mind it's still under work. Forgot to remove that debug stuff. But as you mentioned with injecting the hex into single functions, I'm refactoring right now @Thom-de-Jong "read" function into single object type readings to be able to do it. So stay tuned. This was more or less a progress commit rather than a merge request (still draft).

2023-11-05 09:46 UTC, GwnDaan commented
> This was more or less a progress commit rather than a merge request (still draft).

Hahah no worries, you requested my review twice so I thought maybe you were in a hurry and wanted some feedback 😄. Other than that sounds good, looking forward to the changes!

2023-11-05 10:23 UTC, JannesBrands commented
Ah lol hahah, yep. I got confused to assign reviewers with #28 .  So I was wondering why you are assigned. Later I found out it was this PR and I confused the tabs in chrome and I reassigned you. But thank you for your review!

2023-11-16 21:19 UTC, JannesBrands commented on src/object_pool/object_id.rs
> +    }
Im curious for your opinion of this encapsulation to ensure the correctness of attributes that allows or more important, does not allow a null object.

2023-11-18 19:11 UTC, GwnDaan commented on src/object_pool/object_id.rs
> +    }
I like it, though maybe it is simpler to just do:
 ```rs
type NullableObjectId = Option<ObjectId>
```
Then we don't have have to explicitly construct a type and hence it might be easier to use?

2023-11-18 19:17 UTC, merged

2023-11-18 19:20 UTC, GwnDaan commented
What the hell, I didn't do that?!?